export enum POSEntity {
  MST_ACCOUNT = 'MstAccount',
  MST_BRANCH = 'MstBranch',
  MST_BRANCH_ACCESS = 'MstBranchAccess',
  MST_CUSTOMER = 'MstCustomer',
  MST_DISCOUNT = 'MstDiscount',
  MST_DISCOUNT_ITEM = 'MstDiscountItem',
  MST_ITEM = 'MstItem',
  MST_ITEM_COMPONENT = 'MstItemComponent',
  MST_ITEM_GROUP = 'MstItemGroup',
  MST_ITEM_GROUP_ITEM = 'MstItemGroupItem',
  MST_ITEM_INVENTORY = 'MstItemInventory',
  MST_ITEM_PACKAGE = 'MstItemPackage',
  MST_ITEM_PRICE = 'MstItemPrice',
  MST_PAY_TYPE = 'MstPayType',
  MST_PERIOD = 'MstPeriod',
  MST_SUPPLIER = 'MstSupplier',
  MST_TABLE = 'MstTable',
  MST_TABLE_GROUP = 'MstTableGroup',
  MST_TAX = 'MstTax',
  MST_TERM = 'MstTerm',
  MST_UNIT = 'MstUnit',
  MST_TERMINAL = 'MstTerminal',
  MST_USER = 'MstUser',
  MST_USER_FORM = 'MstUserForm',
  MST_PERMISSIONS = 'MstPermissions',
  MST_ACCESS_RIGHT = 'MstAccessRight',
  MST_ROLE = 'MstRole',
  MST_USER_ROLES = 'MstUserRoles',

  SYS_AUDIT_TRAIL = 'SysAuditTrail',
  SYS_FORM = 'SysForm',
  SYS_SETTINGS = 'SysSettings',
  SYS_ORDER_LOCKED = 'SysOrderLocked',
  SYS_NOTIFICATION = 'SysNotification',
  SYS_USER_TERMINAL = 'SysUserTerminal',

  TRN_COLLECTION = 'TrnCollection',
  TRN_COLLECTION_LINE = 'TrnCollectionLine',
  TRN_DEBIT_CREDIT_MEMO = 'TrnDebitCreditMemo',
  TRN_DEBIT_CREDIT_MEMO_LINE = 'TrnDebitCreditMemoLine',
  TRN_DISBURSEMENT = 'TrnDisbursement',
  TRN_JOURNAL = 'TrnJournal',
  TRN_PAX_TABLE = 'TrnPaxTable',
  TRN_PURCHASE_ORDER = 'TrnPurchaseOrder',
  TRN_PURCHASE_ORDER_LINE = 'TrnPurchaseOrderline',
  TRN_ORDER = 'TrnOrder',
  TRN_ORDER_LINE = 'TrnOrderLine',
  TRN_STOCK_COUNT = 'TrnStockCount',
  TRN_STOCK_COUNT_LINE = 'TrnStockCountLine',
  TRN_STOCK_IN = 'TrnStockIn',
  TRN_STOCK_IN_LINE = 'TrnStockInLine',
  TRN_STOCK_OUT = 'TrnStockOut',
  TRN_STOCK_OUT_LINE = 'TrnStockOutLine',
  TRN_SHIFT = 'TrnShift'
}

