import { lazy } from 'react'

export const AdminDashboardPage = lazy(() => import('./page'))
export const BranchPage = lazy(() => import('./branch/page'))
export const PayTypePage = lazy(() => import('./configurations/pay-types/page'))
export const PeriodPage = lazy(() => import('./configurations/periods/page'))
export const TaxPage = lazy(() => import('./configurations/taxes/page'))
export const TermPage = lazy(() => import('./configurations/terms/page'))
export const TerminalPage = lazy(() => import('./configurations/terminals/page'))
export const UnitPage = lazy(() => import('./configurations/units/page'))
export const ChartOfAccountPage = lazy(() => import('./configurations/chart-of-accounts/page'))
export const CustomersPage = lazy(() => import('./customers/page'))
export const DiscountsPage = lazy(() => import('./discounts/page'))
export const StockCountPage = lazy(() => import('./inventory/stock-count/page'))
export const StockInPage = lazy(() => import('./inventory/stock-in/page'))
export const StockOutPage = lazy(() => import('./inventory/stock-out/page'))
export const StocksPage = lazy(() => import('./inventory/stocks/page'))
export const NotificationsPage = lazy(() => import('./notifications/page'))
export const RolesPage = lazy(() => import('./personnel/roles/page'))
export const UsersPage = lazy(() => import('./personnel/users/page'))
export const ItemComponentsPage = lazy(() => import('./catalog/item-components/page'))
export const ItemGroupsPage = lazy(() => import('./catalog/item-groups/page'))
export const ItemsPage = lazy(() => import('./catalog/items/page'))
export const CollectionsPage = lazy(() => import('./collections/page'))
export const DebitCreditCardMemoPage = lazy(() => import('./debit-credit-card-memo/page'))
export const DisbursementPage = lazy(() => import('./disbursement/page'))
export const POSHotelPage = lazy(() => import('./pos-hotel/page'))
export const POSRetailPage = lazy(() => import('./pos-retail/page'))
export const POSTouchPage = lazy(() => import('./pos-touch/page'))
export const ProfilePage = lazy(() => import('./profile/page'))
export const PurchaseOrderPage = lazy(() => import('./purchase-order/page'))
export const ReportsHubPage = lazy(() => import('./reports-hub/page'))
export const SettingsPage = lazy(() => import('./settings/page'))
export const TableGroupPage = lazy(() => import('./table-group/page'))
export const SuppliersPage = lazy(() => import('./suppliers/page'))

